# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from ....testing import assert_equal
from ..dtitk import ATVCGM


def test_ATVCGM_inputs():
    input_map = dict(args=dict(argstr='%s',
    ),
    environ=dict(nohash=True,
    usedefault=True,
    ),
    flo_file=dict(argstr='-subject %s',
    position=2,
    ),
    ftol_val=dict(argstr='-ftol %f',
    mandatory=False,
    position=7,
    ),
    ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    in_trans=dict(mandatory=False,
    ),
    out_trans=dict(argstr='-outTrans %s',
    genfile=True,
    ),
    ref_file=dict(argstr='-template %s',
    position=1,
    ),
    sep_x_val=dict(argstr='-sep %f',
    mandatory=False,
    position=4,
    ),
    sep_y_val=dict(argstr='%f',
    mandatory=False,
    position=5,
    ),
    sep_z_val=dict(argstr='%f',
    mandatory=False,
    position=6,
    ),
    sm_option_val=dict(argstr='-SMOption %s',
    position=3,
    ),
    terminal_output=dict(nohash=True,
    ),
    )
    inputs = ATVCGM.input_spec()

    for key, metadata in list(input_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(inputs.traits()[key], metakey), value


def test_ATVCGM_outputs():
    output_map = dict(out_trans=dict(),
    )
    outputs = ATVCGM.output_spec()

    for key, metadata in list(output_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
