# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from ....testing import assert_equal
from ..dtitk import DtiDiffeomorphicReg


def test_DtiDiffeomorphicReg_inputs():
    input_map = dict(args=dict(argstr='%s',
    ),
    environ=dict(nohash=True,
    usedefault=True,
    ),
    flo_file=dict(argstr='%s',
    mandatory=True,
    position=2,
    ),
    ftol_val=dict(argstr='%f',
    position=6,
    ),
    ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    initial_val=dict(argstr='%i',
    mandatory=True,
    position=4,
    ),
    iteration_val=dict(argstr='%i',
    mandatory=True,
    position=5,
    ),
    mask_file=dict(argstr='%s',
    mandatory=True,
    position=3,
    ),
    ref_file=dict(argstr='%s',
    mandatory=True,
    position=1,
    ),
    terminal_output=dict(nohash=True,
    ),
    )
    inputs = DtiDiffeomorphicReg.input_spec()

    for key, metadata in list(input_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(inputs.traits()[key], metakey), value


def test_DtiDiffeomorphicReg_outputs():
    output_map = dict(out_trans=dict(),
    )
    outputs = DtiDiffeomorphicReg.output_spec()

    for key, metadata in list(output_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
