# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from ....testing import assert_equal
from ..dtitk import TVResample


def test_TVResample_inputs():
    input_map = dict(args=dict(argstr='%s',
    ),
    environ=dict(nohash=True,
    usedefault=True,
    ),
    ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    in_file=dict(argstr='-in %s',
    mandatory=True,
    ),
    out_file=dict(argstr='-out %s',
    genfile=True,
    ),
    size_val_x=dict(argstr='-size %i',
    mandatory=True,
    position=1,
    ),
    size_val_y=dict(argstr='%i',
    mandatory=True,
    position=2,
    ),
    size_val_z=dict(argstr='%i',
    mandatory=True,
    position=3,
    ),
    terminal_output=dict(nohash=True,
    ),
    vsize_val_x=dict(argstr='-vsize %f',
    mandatory=True,
    position=4,
    ),
    vsize_val_y=dict(argstr='%f',
    mandatory=True,
    position=5,
    ),
    vsize_val_z=dict(argstr='%f',
    mandatory=True,
    position=6,
    ),
    )
    inputs = TVResample.input_spec()

    for key, metadata in list(input_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(inputs.traits()[key], metakey), value


def test_TVResample_outputs():
    output_map = dict(out_file=dict(),
    )
    outputs = TVResample.output_spec()

    for key, metadata in list(output_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
