# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from ....testing import assert_equal
from ..stats import ExtractRoiStatistics


def test_ExtractRoiStatistics_inputs():
    input_map = dict(ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    in_file=dict(argstr='%s',
    mandatory=True,
    ),
    in_label=dict(mandatory=False,
    ),
    in_threshold=dict(argstr='%f',
    mandatory=False,
    ),
    roi_file=dict(argstr='%s',
    mandatory=True,
    ),
    weight_file=dict(argstr='%s',
    mandatory=False,
    ),
    )
    inputs = ExtractRoiStatistics.input_spec()

    for key, metadata in list(input_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(inputs.traits()[key], metakey), value


def test_ExtractRoiStatistics_outputs():
    output_map = dict(out_array=dict(),
    )
    outputs = ExtractRoiStatistics.output_spec()

    for key, metadata in list(output_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
