# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from ....testing import assert_equal
from ..utils import WriteArrayToCsv


def test_WriteArrayToCsv_inputs():
    input_map = dict(ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    in_array=dict(exists=True,
    mandatory=True,
    ),
    in_name=dict(mandatory=True,
    ),
    )
    inputs = WriteArrayToCsv.input_spec()

    for key, metadata in list(input_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(inputs.traits()[key], metakey), value


def test_WriteArrayToCsv_outputs():
    output_map = dict(out_file=dict(),
    )
    outputs = WriteArrayToCsv.output_spec()

    for key, metadata in list(output_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
