# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from ....testing import assert_equal
from ..fmri import RestingStatefMRIPreprocess


def test_RestingStatefMRIPreprocess_inputs():
    input_map = dict(args=dict(argstr='%s',
    ),
    environ=dict(nohash=True,
    usedefault=True,
    ),
    ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    in_fmri=dict(argstr='%s',
    mandatory=True,
    position=3,
    ),
    in_parcellation=dict(argstr='%s',
    mandatory=True,
    position=8,
    ),
    in_t1=dict(argstr='%s',
    mandatory=True,
    position=4,
    ),
    in_tissue_segmentation=dict(argstr='%s',
    mandatory=True,
    position=7,
    ),
    output_type=dict(),
    terminal_output=dict(nohash=True,
    ),
    )
    inputs = RestingStatefMRIPreprocess.input_spec()

    for key, metadata in list(input_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(inputs.traits()[key], metakey), value


def test_RestingStatefMRIPreprocess_outputs():
    output_map = dict(out_atlas_fmri=dict(genfile=True,
    ),
    out_corrected_fmri=dict(genfile=True,
    ),
    out_fmri_to_t1_transformation=dict(genfile=True,
    ),
    out_motioncorrected_file=dict(mandatory=True,
    ),
    out_mrp_file=dict(mandatory=True,
    ),
    out_raw_fmri_csf=dict(mandatory=True,
    ),
    out_raw_fmri_gm=dict(mandatory=True,
    ),
    out_raw_fmri_wm=dict(mandatory=True,
    ),
    out_rms_file=dict(mandatory=True,
    ),
    out_spike_file=dict(mandatory=True,
    ),
    )
    outputs = RestingStatefMRIPreprocess.output_spec()

    for key, metadata in list(output_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
