# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from ....testing import assert_equal
from ..utils import SplitB0DWIsFromFile


def test_SplitB0DWIsFromFile_inputs():
    input_map = dict(ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    in_bval=dict(mandatory=True,
    ),
    in_bval_threshold=dict(mandatory=False,
    usedefault=True,
    ),
    in_bvec=dict(mandatory=True,
    ),
    in_file=dict(mandatory=True,
    ),
    )
    inputs = SplitB0DWIsFromFile.input_spec()

    for key, metadata in list(input_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(inputs.traits()[key], metakey), value


def test_SplitB0DWIsFromFile_outputs():
    output_map = dict(out_B0s=dict(),
    out_DWIs=dict(),
    out_all=dict(),
    out_indices=dict(),
    )
    outputs = SplitB0DWIsFromFile.output_spec()

    for key, metadata in list(output_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
