# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from ....testing import assert_equal
from ..io import Pct2Dcm


def test_Pct2Dcm_inputs():
    input_map = dict(args=dict(argstr='%s',
    ),
    environ=dict(nohash=True,
    usedefault=True,
    ),
    ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    in_umap_file=dict(argstr='%s',
    mandatory=True,
    position=0,
    ),
    in_umap_name=dict(argstr='%s',
    mandatory=True,
    position=2,
    ),
    in_ute_umap_dir=dict(argstr='%s',
    mandatory=True,
    position=1,
    ),
    terminal_output=dict(nohash=True,
    ),
    )
    inputs = Pct2Dcm.input_spec()

    for key, metadata in list(input_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(inputs.traits()[key], metakey), value


def test_Pct2Dcm_outputs():
    output_map = dict(output_file=dict(),
    )
    outputs = Pct2Dcm.output_spec()

    for key, metadata in list(output_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
