# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from ....testing import assert_equal
from ..dtitk import Affine3Dtool


def test_Affine3Dtool_inputs():
    input_map = dict(args=dict(argstr='%s',
    ),
    comp_file=dict(argstr='-compose %s',
    ),
    environ=dict(nohash=True,
    usedefault=True,
    ),
    ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    in_file=dict(argstr='-in %s',
    ),
    out_file=dict(argstr='-out %s',
    genfile=True,
    ),
    terminal_output=dict(nohash=True,
    ),
    )
    inputs = Affine3Dtool.input_spec()

    for key, metadata in list(input_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(inputs.traits()[key], metakey), value


def test_Affine3Dtool_outputs():
    output_map = dict(out_file=dict(),
    )
    outputs = Affine3Dtool.output_spec()

    for key, metadata in list(output_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
