# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from ....testing import assert_equal
from ..io import Dtitk2Fsl


def test_Dtitk2Fsl_inputs():
    input_map = dict(ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    in_file=dict(argstr='%s',
    mandatory=True,
    ),
    )
    inputs = Dtitk2Fsl.input_spec()

    for key, metadata in list(input_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(inputs.traits()[key], metakey), value


def test_Dtitk2Fsl_outputs():
    output_map = dict(out_file=dict(argstr='%s',
    name_source=['in_file'],
    name_template='%s_nii',
    ),
    )
    outputs = Dtitk2Fsl.output_spec()

    for key, metadata in list(output_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
