# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from ....testing import assert_equal
from ..distortion import DistortionGenerator


def test_DistortionGenerator_inputs():
    input_map = dict(bval_file=dict(argstr='%s',
    mandatory=True,
    ),
    bvec_file=dict(argstr='%s',
    mandatory=True,
    ),
    ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    stddev_rotation_val=dict(argstr='%f',
    ),
    stddev_shear_val=dict(argstr='%f',
    ),
    stddev_translation_val=dict(argstr='%f',
    ),
    )
    inputs = DistortionGenerator.input_spec()

    for key, metadata in list(input_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(inputs.traits()[key], metakey), value


def test_DistortionGenerator_outputs():
    output_map = dict(aff_files=dict(),
    bval_files=dict(),
    bvec_files=dict(),
    )
    outputs = DistortionGenerator.output_spec()

    for key, metadata in list(output_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
