# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from ....testing import assert_equal
from ..filters import CropImage


def test_CropImage_inputs():
    input_map = dict(args=dict(argstr='%s',
    ),
    environ=dict(nohash=True,
    usedefault=True,
    ),
    ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    in_file=dict(argstr='-i %s',
    mandatory=True,
    ),
    mask_file=dict(argstr='-m %s',
    ),
    out_file=dict(argstr='-o %s',
    name_source=['in_file'],
    name_template='%s_cropped',
    ),
    output_type=dict(),
    terminal_output=dict(nohash=True,
    ),
    )
    inputs = CropImage.input_spec()

    for key, metadata in list(input_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(inputs.traits()[key], metakey), value


def test_CropImage_outputs():
    output_map = dict(out_file=dict(),
    )
    outputs = CropImage.output_spec()

    for key, metadata in list(output_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
