# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from ....testing import assert_equal
from ..dtitk import DfRightComposeAffine


def test_DfRightComposeAffine_inputs():
    input_map = dict(aff_file=dict(argstr='-aff %s',
    mandatory=True,
    ),
    args=dict(argstr='%s',
    ),
    def_file=dict(argstr='-df %s',
    mandatory=True,
    ),
    environ=dict(nohash=True,
    usedefault=True,
    ),
    ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    out_file=dict(argstr='-out %s',
    genfile=True,
    ),
    terminal_output=dict(nohash=True,
    ),
    )
    inputs = DfRightComposeAffine.input_spec()

    for key, metadata in list(input_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(inputs.traits()[key], metakey), value


def test_DfRightComposeAffine_outputs():
    output_map = dict(out_file=dict(),
    )
    outputs = DfRightComposeAffine.output_spec()

    for key, metadata in list(output_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
