# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from ....testing import assert_equal
from ..stats import ComputeDiceScore


def test_ComputeDiceScore_inputs():
    input_map = dict(ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    in_file1=dict(argstr='%s',
    mandatory=True,
    ),
    in_file2=dict(argstr='%s',
    mandatory=True,
    ),
    )
    inputs = ComputeDiceScore.input_spec()

    for key, metadata in list(input_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(inputs.traits()[key], metakey), value


def test_ComputeDiceScore_outputs():
    output_map = dict(out_dict=dict(),
    )
    outputs = ComputeDiceScore.output_spec()

    for key, metadata in list(output_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
