# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from ....testing import assert_equal
from ..dtitk import DTITKBinaryThresholdImageFilter


def test_DTITKBinaryThresholdImageFilter_inputs():
    input_map = dict(args=dict(argstr='%s',
    ),
    environ=dict(nohash=True,
    usedefault=True,
    ),
    ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    in_file=dict(argstr='%s',
    mandatory=True,
    position=1,
    ),
    inside=dict(argstr='%f',
    mandatory=True,
    position=5,
    ),
    lower_val=dict(argstr='%f',
    mandatory=True,
    position=3,
    ),
    out_file=dict(argstr='%s',
    genfile=True,
    position=2,
    ),
    outside=dict(argstr='%f',
    mandatory=True,
    position=6,
    ),
    terminal_output=dict(nohash=True,
    ),
    upper_val=dict(argstr='%f',
    mandatory=True,
    position=4,
    ),
    )
    inputs = DTITKBinaryThresholdImageFilter.input_spec()

    for key, metadata in list(input_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(inputs.traits()[key], metakey), value


def test_DTITKBinaryThresholdImageFilter_outputs():
    output_map = dict(out_file=dict(),
    )
    outputs = DTITKBinaryThresholdImageFilter.output_spec()

    for key, metadata in list(output_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
