# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from ....testing import assert_equal
from ..dtitk import Affine3DShapeAverage


def test_Affine3DShapeAverage_inputs():
    input_map = dict(args=dict(argstr='%s',
    ),
    environ=dict(nohash=True,
    usedefault=True,
    ),
    file_list=dict(argstr='%s',
    position=1,
    ),
    ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    inverse_flag=dict(argstr='%i',
    exists=True,
    position=4,
    ),
    out_file=dict(argstr='%s',
    genfile=True,
    position=3,
    ),
    ref_file=dict(argstr='%s',
    position=2,
    ),
    terminal_output=dict(nohash=True,
    ),
    )
    inputs = Affine3DShapeAverage.input_spec()

    for key, metadata in list(input_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(inputs.traits()[key], metakey), value


def test_Affine3DShapeAverage_outputs():
    output_map = dict(out_file=dict(),
    )
    outputs = Affine3DShapeAverage.output_spec()

    for key, metadata in list(output_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
