# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from ....testing import assert_equal
from ..qc import FmriQcPlot


def test_FmriQcPlot_inputs():
    input_map = dict(ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    in_mrp_file=dict(mandatory=True,
    ),
    in_raw_fmri=dict(mandatory=True,
    ),
    in_raw_fmri_csf=dict(mandatory=True,
    ),
    in_raw_fmri_gm=dict(mandatory=True,
    ),
    in_raw_fmri_wm=dict(mandatory=True,
    ),
    in_rms_file=dict(mandatory=True,
    ),
    in_spike_file=dict(mandatory=True,
    ),
    )
    inputs = FmriQcPlot.input_spec()

    for key, metadata in list(input_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(inputs.traits()[key], metakey), value


def test_FmriQcPlot_outputs():
    output_map = dict(out_file=dict(genfile=True,
    ),
    )
    outputs = FmriQcPlot.output_spec()

    for key, metadata in list(output_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
