# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from ....testing import assert_equal
from ..stats import CalculateAffineDistances


def test_CalculateAffineDistances_inputs():
    input_map = dict(ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    transformation1_list=dict(mandatory=True,
    ),
    transformation2_list=dict(mandatory=True,
    ),
    )
    inputs = CalculateAffineDistances.input_spec()

    for key, metadata in list(input_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(inputs.traits()[key], metakey), value


def test_CalculateAffineDistances_outputs():
    output_map = dict(out_array=dict(),
    )
    outputs = CalculateAffineDistances.output_spec()

    for key, metadata in list(output_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
