# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from ....testing import assert_equal
from ..qc import InterSliceCorrelationPlot


def test_InterSliceCorrelationPlot_inputs():
    input_map = dict(bval_file=dict(argstr='%s',
    mandatory=False,
    ),
    ignore_exception=dict(nohash=True,
    usedefault=True,
    ),
    in_file=dict(argstr='%s',
    mandatory=True,
    ),
    )
    inputs = InterSliceCorrelationPlot.input_spec()

    for key, metadata in list(input_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(inputs.traits()[key], metakey), value


def test_InterSliceCorrelationPlot_outputs():
    output_map = dict(out_file=dict(genfile=True,
    ),
    )
    outputs = InterSliceCorrelationPlot.output_spec()

    for key, metadata in list(output_map.items()):
        for metakey, value in list(metadata.items()):
            yield assert_equal, getattr(outputs.traits()[key], metakey), value
